### ISSUE TITLE
访问路径/list，返回401页面

### ISSUE THREAD

**Issue by chenhuping** [shigen-fu/file-server#1]
![image](https://github.com/shigen-fu/file-server/assets/38783289/78be072c-9ee5-4117-b9c8-6367d8241625)
![image](https://github.com/shigen-fu/file-server/assets/38783289/3e0ab9e0-a9e9-4ec0-836d-f96ea7f9dc36)
你好作者，能否去掉这个before_reques校验

**Comment by shigen-fu** [comment]
你好 是可以的，新版本已经删除了对应的配置。这样设计主要是已经有服务放在公网了，担心文件的安全问题，感谢您的反馈。
<img width="948" alt="image" src="https://github.com/shigen-fu/file-server/assets/108673112/27bcaecf-2052-4135-88cf-6dedbed2cf83">
新版本提交记录：https://github.com/shigen-fu/file-server/commit/34ca826ee54ee86fa31efc5e083c020b5a5be6d7
